[[section-introduction-and-goals]]
== Introduction and Goals

En este trabajo se intentara desarrollar un sistema para facilitar encuentros entre amigos utilizando nuevas tecnologías. De esta forma permitirá
avisar a un usuario cuándo tiene amigos cerca para que puedan entrar en contacto.

=== Requirements Overview

* Implementación de una aplicación web que funcionará en un servidor en el que se almacenará información sobre localizaciones.
* La aplicación permitirá que los usuarios puedan gestionar y visualizar sus localizaciones y también incluirá opciones de administración para gestionar usuarios y monitorizar el estado del servidor.
* Implementación de una aplicación que funcionará en el dispositivo móvil de los usuarios enviando localizaciones al servidor y recibiendo notificaciones de usuarios conocidos cercanos.
* La aplicación que actúa como servidor almacenará la información mínima necesaria sobre un usuario, el resto de información del usuario, como sus amigos, será consultada en el pod de dicho usuario
* El sistema será desplegable desde contenedores docker y también estará desplegada en un servicio en la nube como heroku.
* La aplicación móvil desplegada también incluirá un sistema de monitorización.
* Se desarrollarán pruebas unitarias, de aceptación y de carga que se ejecutarán de forma automatizada a través de un servidor de integración continua.

.Motivaciones
En estas épocas de COVID-19 el uso de mascarilla dificulta el reconocimiento facial. Queremos que el cliente final pueda distinguir a sus amigos aunque lleven mascarilla y puedan interaccionar entre ellos respetando las medidas establecidas.


=== Quality Goals

[options="header",cols="1,2,2"]
|===
|Prioridad|Objetivo|Motivación
| _1_ | _Privacidad_| _Es importante mantener la privacidad de los datos de cada usuario almacenándolos en su propio POD_
| _2_ | _Usabilidad_| _El usuario debe sentirse cómodo usando nuestra aplicación independientemente de sus conocimientos de informática_
| _3_ | _Eficiencia_| _Un tiempo de respuesta largo puede hacer pensar al usuario que la aplicación no funciona y, por tanto, dejar de usarla_
| _4_ | _Portabilidad_| _El usuario podrá correr la aplicación en la mayoría de los dispositivo con SO android_

|===


=== Stakeholders


[options="header",cols="1,2,2"]
|===
|Role/Nombre|Descripción|Expectativas
| _Profesores_ | _<Contact-1>_ | _<Expectation-1>_
| _Usuarios_ | _<Contact-2>_ | _<Expectation-2>_
| _Desarrolladores_ | _<Contact-2>_ | _<Expectation-2>_
|===