[[section-introduction-and-goals]]
== Introducción y objetivos

En este trabajo se intentara desarrollar un sistema para facilitar encuentros entre amigos utilizando nuevas tecnologías. De esta forma permitirá
avisar a un usuario cuándo tiene amigos cerca para que puedan entrar en contacto.

=== Resumen de los requisitos

* Implementación de una aplicación que trabaje con PODs para el almacenaje de la información sobre localizaciones.
* Radarín permitirá que los usuarios puedan gestionar y visualizar sus localizaciones y también incluirá opciones de administración para gestionar usuarios y monitorizar el estado del servidor.
* Implementación de una aplicación móvil que funcionará en el dispositivo móvil de los usuarios enviando localizaciones al servidor y recibiendo notificaciones de usuarios conocidos cercanos.
* Radarin será desplegable desde contenedores docker y también estará desplegada en un servicio en la nube como https://www.heroku.com/[Heroku].
* La aplicación móvil desplegada también incluirá un sistema de monitorización.
* Se desarrollarán pruebas unitarias, de aceptación y de carga que se ejecutarán de forma automatizada a través de un servidor de integración continua.

.Motivaciones
En estas épocas de COVID-19 el uso de mascarilla dificulta el reconocimiento facial. Queremos que el cliente final pueda distinguir a sus amigos aunque lleven mascarilla y puedan interaccionar entre ellos respetando las medidas establecidas.

=== Objetivos de calidad

[options = "header", cols = "1,2,2"]
|===
 Objetivo | Motivación | Prioridad |

 Privacidad |
    Es importante mantener la privacidad de los datos de cada usuario almacenándolos en su propio POD |
        Muy alta |
 Usabilidad |
    El usuario debe sentirse cómodo usando nuestra Radarin independientemente de sus conocimientos de informática |
        Alta |
 Eficiencia |
    Un tiempo de respuesta largo puede hacer pensar al usuario que Radarin no funciona y, por tanto, dejaría de usarla |
        Alta |
 Portabilidad |
    El usuario podrá correr la aplicación movil en la mayoría de los dispositivo móviles|
        Media |
|===

=== _Stakeholders_

[options = "header", cols = "1,2,2"]
|===
 Rol | Descripción | Expectativas |
 Clientes |
    Evaluarán nuestro proyecto |
        Comprobar que Radarin cumple los requerimientos acordados |
 Usuarios y Usuarios registrados |
    Usar la aplicación |
        Uso de Radarin utilizando las diferentes funcionalidades |
 Desarrolladores |
    Encargados de desarrollo y realización de pruebas de Radarin |
        Hacer que Radarin sea funcional cumpliendo los requisitos y requerimientos |
|===