[[section-architecture-constraints]]
== Restricciones de arquitectura

.Restricciones técnicas
[options = "header", cols = "1,2"]
|===
 Restricción | Descripción |
 https://solidproject.org/[_SoLiD_] |
    El uso de solid nos implica que sea una aplicación descentralizada teniendo que tener hacer uso de los POD. |
 Tests |
    Uso obligatorio de pruebas unitarias para probar el buen funcionamiento. |
|===

.Restricciones de organizacíon
[options = "header", cols = "1,2"]
|===
 Restricción | Descripción |
 https://github.com/[GitHub] |
    Nuestro proyecto originalmente está alojado en esta plataforma. |
 Tiempo |
    El desarrollo de todo el proyecto esta limitado, sólo se dispone de 3 meses. |
 Miembros |
    En este proyecto somos 5 estudiantes de la Universidad de Oviedo, con lo cual no podremos centrarnos exclusivamente en este proyecto. |
 Entregas |
    Hay entregas previas a la finalizacion del proyecto, con lo cual es necesario trabajar de forma constante sobre el proyecto. |
|===

.Restricciones de documentation
[options = "header", cols = "1,2"]
|===
 Restricción | Descripción |
 https://arc42.org/[Arc42] |
    Es requisito recomendado su uso para la documentación. |
 https://asciidoctor.org/[AsciiDoctor] |
    Para la creación de nuestra documentación. |
|===
