[[section-solution-strategy]]
== Solution Strategy

.Contenido
Para llevar a cabo el desarrollo de esta aplicación, utilizaremos Javascript junto con su biblioteca React. Se ha llegado a esta decisión dadas 
las recomendaciones del profesorado de la asignatura. Además de esto, nos parece un lenguaje que proporciona grandes facilidades para el proceso 
de desarrollo de aplicaciones web y para su ampliación mediante módulos externos. A su vez, React nos facilitará en gran medida el diseño de
interfaces suprimiendo la mayoría de las dificultades del uso único de Javascript.

Para la comunicación del proyecto y su desarrollo conjunto se utilizará Github, no solo por sus ventajas en cuanto al control de versiones sino
también para la creación de issues para cada integrante del grupo. Github también proporciona una Wiki en la que se llevará a cabo el control
de acuerdos tomados en cada reunión junto con las tareas realizadas desde la reunión previa.

Se utilizará Open Street Map para la visualización de un mapa interactivo, con la cual tenemos mayor experiencia y simplificará esta parte del proyecto.

.Tecnologías
* Javascript: Lenguaje de programación mundialmente conocido para el desarrollo de aplicaciones web.
* React: Librería de Javascript que proporciona facilidades en el diseño de interfaces.
* Github: Tecnología de control de versiones recomendada para el trabajo cooperativo.
* Open Street Map: Proyecto de creación de mapas interactivos y editables.

.Motivaciones
Todas estas tecnologías a las que nos adaptaremos nos ayudarán a mejorar como programadores y desarrolladores de aplicaciones y nos permitirá
adecuernos a los principios de SOLID.