[[section-deployment-view]]

== Perspectiva de despliegue

.Contexto
RadarIn, nuestra aplicación, está orientada a usuarios personales y será desplegada en navegador, tanto en ordenadores personales como en dispositivos móviles.
Concretamente, serán Microsoft Edge y Google Chrome los dos navegadores de referencia, ambos basados en https://www.chromium.org/[Chromium].

.Tecnologías
Los datos del usuario serán almacenados en un https://solidproject.org/users/get-a-pod[POD], siguiendo así las especificaciones del proyecto https://solidproject.org/[SoLiD].
Toda característica de la aplicación dependerá de su homóloga en la plataforma https://www.heroku.com/[Heroku], donde hemos decidido que sea desplegada.

=== Infraestructura

Siguiendo el patrón de diseño de software Modelo-Vista-Controlador, la responsabilidad de manejar las peticiones recibidas desde el usuario será delegada por la vista 
correspondiente a un controlador idealmente común a todas las vistas. No obstante, el usuario exclusivamente podrá mandar peticiones contra su vista correspondiente.

El controlador de la aplicación únicamente accederá al POD del usuario, el cual hará las veces de modelo, con previo consentimiento de dicha persona.

Una arquitectura de una aplicación basada en el patrón Modelo-Vista-Controlador que siga las especificaciones de SoLiD sugiere un desacoplamiento del modelo.
Dependeremos de la plataforma que mantenga el POD en cuestiones como la disponibilidad de los datos, aunque esto ofrece una garantía al usuario de que absolutamente 
ningún dato será guardado en la aplicación RadarIn, dando la confianza de que éstos no serán manipulados de ninguna manera que el usuario no permita explícitamente.

.Sistemas implicados en la infraestructura.
- **Dispositivo de usuario**. Puede ser un dispositivo móvil o un equipo de sobremesa.
- **Heroku**. Sirve de plataforma a la aplicación RadarIn.
- **POD de SoLiD**. Almacena la información del usuario en un servidor de terceros, cuyo almacenamiento tiene que haber sido llevado a cabo por el usuario previamente.

[plantuml, {plantUMLDir}infrastructure, svg]
----
database "POD on SoLiD" {
  [Ubication]
}

node "RadarIn Application on heroku" {
  [View]
  [Controller]
}

User  --> [View]

[View] --> [Controller] : notify
[Controller] --> [View] : update

[Controller] --> [Ubication] : get
----

////

[plantuml, {plantUMLDir}infrastructureOld, svg]
----
cloud "Model (MVC)" {
  database "POD1" {
    [Ubication1]
  }
  database "POD2" {
    [Ubication2]
  }
  database "POD3" {
    [Ubication3]
    [PreviousUbication3]
  }
}

Android_User --> POD2 : manages
iOS_User --> POD1 : manages
Windows_10_User --> POD3 : manages

node "RadarIn Application" {
  package "View (MVC)" {
    [Chrome Mobile]
    [Chrome Desktop]
  }
  [Controller (MVC)]
}

[Chrome Mobile] --> [Controller (MVC)] : notifies
[Chrome Desktop] --> [Controller (MVC)] : notifies
[Controller (MVC)] --> [Chrome Mobile] : updates
[Controller (MVC)] --> [Chrome Desktop] : updates

Android_User  --> [Chrome Mobile] : allows
iOS_User --> [Chrome Mobile] : does_not_allow
Windows_10_User --> [Chrome Desktop] : allows

[Controller (MVC)] --> [Ubication2] : uses
[Controller (MVC)] --> [Ubication3] : uses
----

 ////
