[[section-concepts]]
== Cross-cutting Concepts

=== Conceptos del dominio

* _Usuario: es la persona que usa la aplicación. El sistema almacenará su localización en un instante de tiempo, no almacenará ningún tipo de información que no sea necesaria._
* _Pod: es un repositorio de usuarios que almacenará la información que no se considera mínima del usuario, por ejemplo sus amigos. Sigue las especificaciones SOLID y puede almacenarse en cualquier plataforma. Es el propio usuario el que tiene gestón total de su información._
* _Amigo: un usuario tendrá amigos y le informará (mediante notificaciones) cuando uno de ellos esté cerca._

=== Patrones de arquitectura
_Basamos nuestra aplicación en el patrón arquitectónico MVC, consiste en separar los datos y la lógica de negocio de la aplicación de la representación visual y los canales de comunicación._


=== Experiencia de usuario
==== Diseño de la interfaz de usuario
_La idea de la interfaz es hacerla intuitiva y dirigida para todos los tipos de usuarios. Además buscamos hacerla limpia y bonita estéticamente._
==== Internacionalización
_La idea primera del desarrollo de la aplicación es hacerla en español, ya que es nuestro idioma materno y nos sentimos más comodos para desarrollar la aplicación y la documentación._

=== Seguridad
_Se considera una aplicación segura gracias al uso del protocolo HTTPS. Además, gracias a los PODS los datos del usuario se almacenarán de una forma privada y es el propio usuario el que tiene que dar acceso a estos datos._

=== Desarrollo
==== Construcción
_Respecto a este apartado usaremos el administrador de paquetes Node.js para lograr los objetivos en cuanto a funcionalidad que deseamos._
==== APIs
_Usaremos una API de mapas (OpenStreetMap) para mostrar un mapa al usuario._
==== Migración
_Habrá que desarrollar una aplicación Web y una para móviles, por tanto intentaremos no cambiar mucho en cuanto a desarrollo según se use una plataforma u otra._

=== Recuperación ante un imprevisto
_Gracias al uso de los PODS la recuperación de información no está en riesgo, ya que la información almacenada es independiente de la aplicación y está alojada en otro sitio._

=== Pruebas
_Hemos acordado realizar pruebas exhaustivas cuando la aplicación esté en funcionamiento._




