[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
|===
|Decisión|Ventajas|Desventajas
| _Documentación en español_ | _Mayor velocidad a la hora de crear la documentación y mayor calidad y riqueza del lenguaje_| _No es el idioma mas usado en proyectos_
| _Uso de SOLID_ | _._| _._
| _Uso de Open Street Maps_ | _Parte del grupo ya esta familiarizado con él y nos parece más fácil de usar_| _Al no ser el más utilizado quizá haya problemas a la hora de buscar información o en caso de tener algun error poco común_

|===