[[section-technical-risks]]
== Riesgos y deudas técnicas

_Un problema conocido en compañías de desarrollo de software grandes es cómo balancear la priorización de la capacidad de respuesta a corto plazo con la capacidad de respuesta a largo plazo, específicamente violaciones de arquitectura._

[.text-right]
- https://www.researchgate.net/publication/265822240_Architecture_Technical_Debt_Understanding_Causes_and_a_Qualitative_Model[Architecture Technical Debt. Antonio Martini, Jan Bosch, Michel Chaudron].

En esta sección prevendremos las diferentes vías por las cuales pueden surgir violaciones de arquitectura y ofreceremos una posible solución a estas.

=== Riesgos y medidas

[options = "header", cols = "1,2,2"]
|===
 Deuda técnica | Riesgos | Medidas |
 *SoLiD* |
    El proyecto SoLiD es relativamente nuevo y no tenemos experiencia con él en el equipo. |
        Nos instruiremos mediante todos nuestros recursos disponibles en SoLiD y en todas las tecnologías relacionadas. |
 *POD* |
    El POD almacena la información del usuario en un servidor de terceros, sobre el cual recae la disponibilidad o la consistencia. |
        Procuraremos seguir las especificaciones de SoLiD para intercambiar información con PODs, 
        ya que poco podemos hacer con respecto a algo que es mantenido por un servidor ajeno. |
 *Docker* |
    Utilizaremos Docker para automatizar el despliegue de nuestra aplicación dentro de un contenedor de software servido por Heroku. |
        Nuestra aplicación ha de utilizar herramientas que se integren perfectamente en Docker. |
 *React* |
    React se basa en JavaScript, lenguaje en el cual no tenemos gran experiencia. |
        Nos formaremos en React y en JavaScript hasta tal punto que podamos solventar los problemas venideros durante el desarrollo del proyecto, por ejemplo haciendo cursos. |
 *Node.js* |
    Node.js requiere de un conocimiento en librerías, operaciones asíncronas y dependencias. |
        Buscaremos cuanta más información mejor acerca de cómo utilizar la librería Node.js. |
 *Scala* |
    Scala se trata de una tecnología diseñada para expresar patrones comunes de programación en forma concisa, elegante y con tipos seguros. Nuestra experiencia en esta es nula. |
        Trataremos de aplicarla en nuestro proyecto, aunque si esto consta una complicación mayor, nos replantearemos el uso de esta tecnología. |
|===
